CONTIKI = ../../..

PLATFORMS_ONLY= cc2538dk zoul sky cc26x0-cc13x0

MODULES += os/services/unit-test
MODULES += os/storage/cfs

CONTIKI_PROJECT = test-cfs test-coffee example-coffee
all: $(CONTIKI_PROJECT)

include $(CONTIKI)/Makefile.include
